# vim:ft=kitty

## name:     Nord
## license:  MIT
## upstream: https://www.nordtheme.com/

# Basic colors
foreground              #D8DEE9
background              #2E3440
selection_foreground    #2E3440
selection_background    #D8DEE9

# Cursor (underline style set in kitty.conf)
cursor                  #D8DEE9
cursor_text_color       #2E3440

# URL underline color when hovering
url_color               #88C0D0

# Window borders
active_border_color     #88C0D0
inactive_border_color   #4C566A
bell_border_color       #EBCB8B

# Tab bar
active_tab_foreground   #2E3440
active_tab_background   #88C0D0
inactive_tab_foreground #D8DEE9
inactive_tab_background #3B4252
tab_bar_background      #2E3440

# Normal
color0  #3B4252
color1  #BF616A
color2  #A3BE8C
color3  #EBCB8B
color4  #81A1C1
color5  #B48EAD
color6  #88C0D0
color7  #E5E9F0

# Bright
color8  #4C566A
color9  #BF616A
color10 #A3BE8C
color11 #EBCB8B
color12 #81A1C1
color13 #B48EAD
color14 #8FBCBB
color15 #ECEFF4
